apiVersion: v2
name: ds-policy-engine-ui
description: Static UI for ds-policy-engine (nginx)
type: application
version: "0.0.0"
appVersion: "0.0.0"
keywords:
  - ui
  - policy
  - nginx
maintainers:
  - name: HIRO-MicroDataCenters
